### ISSUE TITLE
Client.obtain_token_by_refresh_token fails when token_item is a str

### ISSUE THREAD

**Issue by jiasli** [AzureAD/microsoft-authentication-library-for-python#297] opened 2021-01-26 09:23 UTC
**Describe the bug**
Even though `Client.obtain_token_by_refresh_token` checks the type of `token_item` at 

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/381fe584df39f69a952d6e685758f93f581c2b96/msal/oauth2cli/oauth2.py#L801-L802

and calls `rt_getter` accordingly, it doesn't check the type of `token_item` at

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/381fe584df39f69a952d6e685758f93f581c2b96/msal/oauth2cli/oauth2.py#L809-L810

to make sure `token_item` is converted to a `dict` before calling `self.on_updating_rt`.

This causes `update_rt` to fail at L248:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0845404ef7ec6a95e0fecf123a815e06dc683d85/msal/token_cache.py#L247-L248

**To Reproduce**
Pass a refresh token in `str` as `token_item` to `Client.obtain_token_by_refresh_token`.

**Expected behavior**
Either:
- `Client.obtain_token_by_refresh_token` should succeed with `token_item` as a `str` either by
  - converting `token_item` to a `dict` before calling `on_updating_rt`
  - forcing `on_updating_rt=False`
- `Client.obtain_token_by_refresh_token` should reject `token_item` as a `str`

**What you see instead**

```
  File "D:\cli\microsoft-authentication-library-for-python\msal\application.py", line 714, in acquire_token_silent
    result = self.acquire_token_silent_with_error(
  File "D:\cli\microsoft-authentication-library-for-python\msal\application.py", line 767, in acquire_token_silent_with_error
    result = self._acquire_token_silent_from_cache_and_possibly_refresh_it(
  File "D:\cli\microsoft-authentication-library-for-python\msal\application.py", line 840, in _acquire_token_silent_from_cache_and_possibly_refresh_it
    return self._acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family(
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\_msal.py", line 17, in _acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family
    return self._acquire_token_silent_by_finding_specific_refresh_token(
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\_msal.py", line 28, in _acquire_token_silent_by_finding_specific_refresh_token
    response = client.obtain_token_by_refresh_token(
  File "D:\cli\microsoft-authentication-library-for-python\msal\oauth2cli\oauth2.py", line 810, in obtain_token_by_refresh_token
    (on_updating_rt or self.on_updating_rt)(token_item, resp[RT])
  File "D:\cli\microsoft-authentication-library-for-python\msal\token_cache.py", line 248, in update_rt
    assert rt_item.get("credential_type") == self.CredentialType.REFRESH_TOKEN
AttributeError: 'str' object has no attribute 'get'
```
**The MSAL Python version you are using**
1.8.0

**Additional context**
This issue is revealed by https://github.com/Azure/azure-cli/pull/16672#discussion_r564294407.

**Comment by rayluo** [comment] 2021-02-02 02:41
@jiasli , thanks for your high quality report. You clearly did your homework! That helps a lot! After examination, I think: (1) this is not a bug inside MSAL, but rather (2) a misusage of `Client.obtain_token_by_refresh_token()` (or its public API `ClientApplication.acquire_token_by_refresh_token()`). Let me explain.

1. First of all, `Client.obtain_token_by_refresh_token()` is an internal API. Its [incoming parameter `token_item` is designed to be either a string or a flexible structure](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.8.0/msal/oauth2cli/oauth2.py#L774-L780) (so that also means one of the proposed workaround "`Client.obtain_token_by_refresh_token` should reject `token_item` as a `str`" would conflict the original design).

   And, why we do not need the string check for the callback `on_updating_rt()`? That is because that callback is also an input parameter, so, it is the caller's responsibility to ensure the `token_item` they fed in, would also be accepted by the `on_updating_rt()` they fed in. The current implementation is flexible to allow the caller to provide a pair of RT and a SUITABLE `on_updating_rt()`, as long as they match each other.

2. For example, this is one of the right usage pattern. The public API level [`ClientApplication.acquire_token_by_refresh_token()` chooses to define an RT as a str](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.8.0/msal/application.py#L957), so it also uses [a proper `on_updating_rt`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.8.0/msal/application.py#L977). It is somewhat tricky, but then again, that was why we wrapped those details inside a public API `acquire_token_by_refresh_token()` which was designed to handle raw RT migration scenario (in other words, this API assumes the incoming RT is a one-time migration, so you won't need an `on_updating_rt()` behavior for it).

   Now my question to you is, under what scenario you would have that "To Reproduce: Pass a refresh token in str as token_item to `Client.obtain_token_by_refresh_token`"? Is it triggered by using public API `acquire_token_by_refresh_token()` for ssh login?

**Comment by jiasli** [comment] 2021-02-02 03:27
Thanks @rayluo for the detailed explanation. 

The required compatibility between the provided RT in `token_item` and `on_updating_rt` answers the initial concern. 

> Now my question to you is, under what scenario you would have that "To Reproduce: Pass a refresh token in str as token_item to `Client.obtain_token_by_refresh_token`"? Is it triggered by using public API `acquire_token_by_refresh_token()` for ssh login?

Yes, exactly. As `acquire_token_by_refresh_token` doesn't expose `kwargs`, I have to pass RT in `str` as `token_item` to `Client.obtain_token_by_refresh_token`. Once `ClientApplication.acquire_token_by_refresh_token` (which is of course the better choice) supports passing `kwargs`, I wouldn't need to call `Client.obtain_token_by_refresh_token` directly and thus not hitting this "issue" anymore.

**Comment by rayluo** [comment] 2021-02-02 03:40
OK then, let's close this Q&A here, and shift our subsequent discussion on the other issue.

**Closed by rayluo** 2021-02-02 03:40 UTC
Labels: answered, question, wontfix

**Comment by jiasli** [comment] 2021-02-02 03:44
By the way, this is exactly why I find the idea of [overriding MSAL internal methods](https://github.com/Azure/azure-cli/blob/b552578cc51df934b8e714bee4bf73f1f279ae21/src/azure-cli-core/azure/cli/core/_msal.py) problematic, as it may be difficult to follow MSAL's internal intricacy and adapt to MSAL's changes.
