### ISSUE TITLE
app.acquire_token_silent(scope, account=None)

### ISSUE THREAD

**Issue by YurongHe** [AzureAD/microsoft-authentication-library-for-python#206] opened 2020-06-10 19:06 UTC
Install msal-1.3.0-py2.py3-none-any.whl
Follow the sample https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/confidential_client_certificate_sample.py

when run app.acquire_token_silent(scope, account=None) got error:
"2020-06-10 12:02:37.0116 UTC | ERROR | Invalid parameter type"

**Comment by abhidnya13** [comment] 2020-06-11 02:14
Also, can you confirm if your scope is a list ? acquire_token_silent expects scope which is the first parameter as a list.

**Comment by YurongHe** [comment] 2020-06-11 03:45
> Also, can you confirm if your scope is a list ? acquire_token_silent expects scope which is the first parameter as a list.

Thanks, change scope to list, the invalid parameter exception is gone. But never gets the token from the cache while the get token code path was called multiple times.

code: 
def get_token_using_msal(self):
        app = msal.ConfidentialClientApplication(
            self.spn.client_id,
            self.spn.client_secret,
            'https://login.microsoftonline.com/' + self.spn.tenant_id,
           )
        # The pattern to acquire a token looks like this.
        result = None

        # Firstly, looks up a token from cache
        # Since we are looking for token for the current app, NOT for an end user,
        # notice we give account parameter as None.
        result = app.acquire_token_silent([azure_constants.AZURE_ARM_SCOPE], account=None)
        if result:
            print('Got token from cache')
        if not result:
            #logging.info("No suitable token exists in cache. Let's get a new one from AAD.")
            result = app.acquire_token_for_client([azure_constants.AZURE_ARM_SCOPE])
            print('got token from client')
        if "access_token" in result:
            return result['access_token']

        else:
            print(result.get("error"))
            print(result.get("error_description"))
            print(result.get("correlation_id"))
Only got 'got token from client from output

How could we get the token from cache?

**Comment by abhidnya13** [comment] 2020-06-11 18:42
Great that it worked for you ! 

For token_cache to work, you will have to persist the tokens somewhere like a disk or db. You will have to provide this location to the msal application in the form of a token cache object. 
You can find more information on how to do that [here](https://msal-python.readthedocs.io/en/latest/#msal.SerializableTokenCache). Once this token cache object is passed to the application, it will be able to store tokens in the cache and retrieve from there on its own.

**Comment by YurongHe** [comment] 2020-06-11 20:27
Thanks. From the sample: https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.3.0/sample/confidential_client_secret_sample.py

In the sample following line: 

> app = msal.ConfidentialClientApplication(
>     config["client_id"], authority=config["authority"],
>     client_credential=config["secret"],
>     # token_cache=...  # Default cache is in memory only.
>                        # You can learn how to use SerializableTokenCache from
>                        # https://msal-python.rtfd.io/en/latest/#msal.SerializableTokenCache
>     )

It states the default cache is memory only. Does it mean no in-memory cache anymore?

**Comment by abhidnya13** [comment] 2020-06-11 22:39
If you are trying to use in-memory cache and chose not to persist it, you still need to pass a TokenCache object but not associate it with any persistence like file or database. It would by default store it in-memory of TokenCache object that you pass to your application. It will however be associated with only that instance of application.

**Comment by navyasric** [comment] 2020-06-23 21:48
Closing this as the issue is answered above.

**Closed by navyasric** 2020-06-23 21:48 UTC
Labels: answered

**Comment by VedAustin** [comment] 2021-03-01 17:24
Took me a bit of digging to get this right:
(for daemon apps):
```python
import msal

cache = msal.SerializableTokenCache()
app = msal.ConfidentialClientApplication(..., token_cache = cache) # in-memory cache
....
```

**Comment by rayluo** [comment] 2021-03-01 18:56
Hi @VedAustin , thanks for getting in touch with us.

1. Can you elaborate what was not right?

2. Were you trying to get the tokens persisted onto disk? (Your current code snippet above is still commented as - and is indeed still using - an in-memory cache. So we are not sure which way you really want.)

3. Lastly, what was the very first document and/or sample that you started with? Once you clarify Q1 and Q2 above, we can then see if we can incorporate those learnings into that first document/sample.

**Comment by VedAustin** [comment] 2021-03-04 15:27
Hi Ray .. originally I was unable to use token cache from memory. I believe without using this argument, `token_cache=cache`, it would generate new tokens every time, even though I did not leave the session. In the code sample that YurongHe had shown above, the token cache object is commented out and it says the default is memory cache. But I dont believe it is the case and the only way to retrieve it from memory, is by passing a token cache object as pointed by abhidnya13.

Another source of confusion for in memory cache that I was struggling with was that, I was hoping that "Azure" would take the responsibility of managing tokens - i.e. retrieve tokens if they have not expired else generate new tokens. However it looks like that responsibility has been passed on to developers. The in-memory tokens dont really work when we have written the part of accessing token in a script and imported as a module. I had to persist this in an Azure blob - which is fine but creating a storage account to store 10 bytes of data looks over the top. :)

**Comment by rayluo** [comment] 2021-03-04 19:59
@VedAustin 

> Another source of confusion for in memory cache that I was struggling with was that, I was hoping that "Azure" would take the responsibility of managing tokens - i.e. retrieve tokens if they have not expired else generate new tokens. However it looks like that responsibility has been passed on to developers.

Let's clarify this first. The "Azure (Azure ActiveDirectory i.e. AAD)" in the cloud will only generate/issue new tokens for you. It is you as the developer who would need to decide whether to maintain a cache with your app, OUTSIDE of AAD, so that your app does not need to talk to AAD every time. This is true, regardless of whether your app is running locally on your desktop, or running remotely as an Azure Function in the cloud. Azure Function and AAD are still 2 different entities.

`Your app <---> AAD`

> In the code sample that YurongHe had shown above, the token cache object is commented out and it says the default is memory cache. But I dont believe it is the case and the only way to retrieve it from memory, is by passing a token cache object as pointed by abhidnya13.

Taking a close look, that earlier comment "If you are trying to use in-memory cache and chose not to persist it, you still need to pass a TokenCache object but not associate it with any persistence like file or database" seems inaccurate. <sub>(Since YurongHe did not respond after that comment, we do not know what was the real issue in her case.)</sub> But I want to clarify that, without an argument `token_cache=cache`, there is still an in-memory cache. Here, "in-memory" means it lasts for the entire lifetime of the `app` object created by `app = ConfidentialClientApplication(...)` (or by `app = PublicClientApplication(...)`, for that matter). So, in [the exact code snippet you provided above](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/206#issuecomment-788126160), there is no need to explicitly use a `token_cache=cache`, it wouldn't make a difference.

However, you'd need to take into consideration of how/where your app runs. Since your app is an Azure Function, the `app` object is ephemeral, it is created and destroyed for each request, so its default in-memory cache is also gone after each request. That's why you'd have to use an explicit `SerializableTokenCache()`, AND somehow persist it somewhere else. Looks like you've managed to use Azure blob, which can do the job.

If this answers all your question, let us know. We'll see whether we can add this into the "in-memory" notion in our samples, assuming that was where you started your project.

**Comment by VedAustin** [comment] 2021-03-05 02:32
Great explanation Ray! Really appreciate taking the time to answer this in great detail. Let me double check on the in-memory cache stuff again and get back to you .. hopefully with a reproducible code.

**Comment by kevindixon** [comment] 2021-08-24 16:06
@rayluo from what I can see, the cache does **NOT** work as you describe, at least for `PublicClientApplication` when you don't provide an account:

```python
import msal

some_scopes = ['ascope']
app_id = 'myappid'
my_authority = 'https://login.microsoftonline.com/mytenantid'

# Create an app session
app = msal.PublicClientApplication(client_id=app_id, authority=my_authority)
result = None

# Acquire token interactively
result = app.acquire_token_interactive(scopes=some_scopes, port=8811)
assert result
assert 'access_token' in result
# <-- We're all good here!

# Acquire token silently in same app session
result = app.acquire_token_silent(scopes=some_scopes, account=None)
# <-- Booo... result is None
assert result  # <-- Boom
assert 'access_token' in result
```

From a very quick look at the code, it looks as though items in the cache have a key that includes the account id, so unless you provide an account it always fails lookup. Or have I missed something?

If you *DO* select an account, its all good:

```python
import msal

some_scopes = ['ascope']
app_id = 'myappid'
my_authority = 'https://login.microsoftonline.com/mytenantid'

# Create an app session
app = msal.PublicClientApplication(client_id=app_id, authority=my_authority)
result = None

# Acquire token interactively
result = app.acquire_token_interactive(scopes=some_scopes, port=8811)
assert result
assert 'access_token' in result
# <-- We're all good here!

# Get an account
accounts = app.get_accounts(username=None)
account = accounts[0]  # Simulate user selection

# Acquire token silently in same app session
result = app.acquire_token_silent(scopes=some_scopes, account=account)
assert result
assert 'access_token' in result
# <-- We're all good here!
```

I want to avoid having to ask the user for an account, but still utilise an *in memory* cache..... how do I do this?

**Comment by rayluo** [comment] 2021-08-24 22:30
@kevindixon 
1. That is because the [`acquire_token_silent(..., account=...)` has different meaning when `account=None` and `account=chosen_account`, as documented here](https://msal-python.readthedocs.io/en/latest/#msal.PublicClientApplication.acquire_token_silent_with_error). When using PublicClientApplication, you can not omit the account parameter. This conversation was for `ConfidentialClientApplication.acquire_token_for_client()` (now I've changed this conversation's title accordingly).
2. I'm going to lock this conversation. Please start a new topic for your separate question "I want to avoid having to ask the user for an account, but still utilise an in memory cache..... how do I do this?".
