### ISSUE TITLE
Function _get_instance_metadata is hardcoded to Azure Public URL

### ISSUE THREAD

**Issue by lm-sig** [AzureAD/microsoft-authentication-library-for-python#578] opened 2023-07-13 13:16 UTC
**Describe the bug**
The function in application.py, '_get_instance_metadata', is hard coded to point to the Azure Public URL of 'login.microsoftonline.com' and this is a problem for those that use other clouds (ex. AzureUSGovernment) and access to the Public URL is not permitted or allowed. The function should work similar to others were the URL is passed in as an argument.

**To Reproduce**
1. Use any Ansible azcollection module.
2. Set "cloud_environment" or AZURE_CLOUD_ENVIRONMENT to any cloud besides Azure Public.
3. Set AZURE_AUTHORITY_HOST=https://login.microsoftonline.us
4. Block DNS resolution and/or network connectivity to any login.microsoftonline.com address. (Set to 127.0.0.1 in your hosts file if you need to test)
5. Run a playbook that calls a module in the azcollection.
6. The azcollection module task will fail with an error of "name or service not known" like there is a DNS problem or "connection refused" if a firewall is blocking.

**Expected behavior**
Ansible modules are able to authenticate with a non-Azure Public cloud.

**What you see instead**
"[Errno -2] Name or service not known"

**The MSAL Python version you are using**
1.20.0

**Additional context**
This function was introduced in MSAL 1.19.0. Previous 'azcollection' packages pulled in 1.18.0 and worked as expected.

If I update my copy of 1.20.0 to replace ".com" with ".us" the Ansible modules work.

**Comment by rayluo** [comment] 2023-07-13 23:08
Thanks for reporting your concern.

We are trying to figure out why this is the case.

> Additional context
This function was introduced in MSAL 1.19.0. Previous 'azcollection' packages pulled in 1.18.0 and worked as expected.

While that internal function was indeed the result of a [refactoring](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/496/files#diff-4d32d284fa6acf43894719eff11cb366e5969e0b61593bfd00c68a4cf9c441caR1052-L1020) which was shipped in MSAL Python 1.19, the same behavior has long existed, probably since day 1. But then, your statement of "Previous 'azcollection' packages pulled in 1.18.0 and worked as expected" contradicted with our understanding here.

We do not have ansible or azcollection environments in hand. But we believe the following one-liner shall be an equivalent and simpler way to reproduce the issue using MSAL Python only. It calls MSAL's `get_accounts()` which will in turn trigger that metadata behavior.

```bash
python -c "import logging, msal; logging.basicConfig(level=logging.DEBUG); print(msal.__version__); msal.PublicClientApplication('client_id', authority='https://login.microsoftonline.us/common').get_accounts()"
```

Running it in a virtual environment with MSAL Python 1.18 or 1.19+ installed, you shall always see it printing some logs, and the last line of logs will indeed contains the public cloud login.microsoftonline **.com**:

> DEBUG:urllib3.connectionpool:https://login.microsoftonline **.com**:443 "GET /common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize HTTP/1.1" 200 945

MSAL 1.19 introduced [a new parameter to turn off this behavior](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.params.instance_discovery). But then again, your error description contradicted with our understanding, so, we do not know whether you were actually running into a different issue.

**Comment by lm-sig** [comment] 2023-07-13 23:58
I am not directly using MSAL. Ansible modules call the Azure Python SDK and the Azure Python SDK calls MSAL. I'll look into seeing if either the Ansible modules or the Azure Python SDK can be updated to pass the parameter offered in 1.19+ and report the results. It may take up to a week. Thanks for the pointer.

**Comment by rayluo** [comment] 2023-07-23 19:44
Closing because it is not actionable from MSAL side. Feel free to reopen if there will be any follow-up that needs our attention.

**Closed by rayluo** 2023-07-23 19:44 UTC
Labels: requires more info

**Comment by lm-sig** [comment] 2023-08-07 21:36
Setting "instance_discovery=False" in the function call helps. Thanks for the pointer.

Resolution:
- The Ansible collection has a requirements.txt setting a dependency on azure-identity==1.7.0 (Oct. 14, 2021)
- The MSAL library added "instance_discovery" in version 1.19 (Sept. 20, 2022)
- The azure-identity library gained support to passing "instance_discovery" in version 1.13.0 (May 11, 2023)
- I have filed a feature request with the [Ansible collection GitHub](https://github.com/ansible-collections/azure/issues/1236) to add support for a newer azure-identity library and setting the "instance_discovery" toggle. Possibly if the "AZURE_AUTHORITY_HOSTS" environment variable is set.

Thanks again for your time.

**Comment by rayluo** [comment] 2023-08-07 22:30
We just did our job. It is you, @lm-sig , that started your quest and saw it through. The community will thank you for your contribution.
